name: Compile examples
'on':
  push:
    branches:
    - master
    - main
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Compile the Documents
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          tikz-bricks.tex
          titleimage-is.tex
          example.tex
    - name: Render the preview
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends poppler-utils
        pdftoppm -png -f 1 -l 1 ./titleimage-is.pdf example
    - name: Publish to gh-pages
      run: |
        sudo chown -R "$(id -u):$(id -g)" .
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -f "tikz-bricks.pdf" "titleimage-is.pdf" "example.pdf" "example-1.png"
        git commit -m "Newly compiled data"
        git push --force origin HEAD:gh-pages
